Infrastructure/ViewModels/ProductViewModel.cs
using CoreBusiness;

namespace Infrastructure.ViewModels
{
    public class ProductViewModel
    {
        public IEnumerable<Category> categories { get; set; } = Enumerable.Empty<Category>();
        public Product? product { get; set; }
    }
}

Infrastructure/ViewModels/SalesViewModel.cs
using CoreBusiness;
using Infrastructure.ViewModels.Validations;
using System.ComponentModel.DataAnnotations;

namespace Infrastructure.ViewModels
{
    public class SalesViewModel
    {
        public int? SelectedCategoryId { get; set; }
        public int SelectedProductId { get; set; }
        public IEnumerable<Category> Categories { get; set; } = new List<Category>();
        [Display(Name = "Quantity")]
        [Range(0,int.MaxValue)]
        [SalesViewModel_EnsureProperQuantity]
        public int QuantityToSell { get; set; }
    }
}

Infrastructure/Controllers/ProductsController.cs
using CoreBusiness;
using Microsoft.AspNetCore.Mvc;
//using Infrastructure.Models;
using Infrastructure.ViewModels;
using UseCases.interfaces;
using UseCases.ProductsUseCases;
using Microsoft.AspNetCore.Authorization;

namespace Infrastructure.Controllers
{
    [Authorize(Policy = "Inventory")]
    public class ProductsController : Controller
    {
        private readonly IAddProductUseCase addProductUseCase;
        private readonly IDeleteProductUseCase deleteProductUseCase;
        private readonly IViewProductsUseCase viewProductsUseCase;
        private readonly IViewSelectedProductUseCase viewSelectedProductUseCase;
        private readonly IEditProductUseCase editProductUseCase;
        private readonly IViewCategoriesUseCase viewCategoriesUseCase;

        public ProductsController(IAddProductUseCase addProductUseCase,
                                  IDeleteProductUseCase deleteProductUseCase,
                                  IViewProductsUseCase viewProductsUseCase,
                                  IViewSelectedProductUseCase viewSelectedProductUseCase,
                                  IEditProductUseCase editProductUseCase,
                                  IViewCategoriesUseCase viewCategoriesUseCase)
        {
            this.addProductUseCase = addProductUseCase;
            this.deleteProductUseCase = deleteProductUseCase;
            this.viewProductsUseCase = viewProductsUseCase;
            this.viewSelectedProductUseCase = viewSelectedProductUseCase;
            this.editProductUseCase = editProductUseCase;
            this.viewCategoriesUseCase = viewCategoriesUseCase;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var products = viewProductsUseCase.execute(loadCategory: true);
            return View(products);
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "add";
            ProductViewModel productViewModel = new ProductViewModel()
            {
                categories = viewCategoriesUseCase.Execute()
            };
            return View(productViewModel);
        }

        [HttpPost]
        public IActionResult Add([FromForm] ProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
                addProductUseCase.Execute(productViewModel.product);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Action = "add";

            productViewModel.categories = viewCategoriesUseCase.Execute();
            return View(productViewModel);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            ViewBag.Action = "edit";

            var productViewModel = new ProductViewModel
            {
                product = viewSelectedProductUseCase.Execute(id.HasValue?id.Value:0),
                categories = viewCategoriesUseCase.Execute()
            };
            return View(productViewModel);
        }

        [HttpPost]
        public IActionResult Edit(ProductViewModel productViewModel)
        {

            if (ModelState.IsValid && productViewModel.product!=null)
            {
                var product = new Product
                {
                    ProductId=productViewModel.product.ProductId,
                    Quantity=productViewModel.product.Quantity,
                    Price=productViewModel.product.Price,
                    CategoryId=productViewModel.product.CategoryId,
                    Name=productViewModel.product.Name
                };

                editProductUseCase.Execute(productViewModel.product.ProductId, productViewModel.product);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Action = "edit";

            productViewModel.categories = viewCategoriesUseCase.Execute();
            return View(productViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            deleteProductUseCase.Execute(id);
            return RedirectToAction(nameof(Index));
        }

        

    }
}

Infrastructure/Controllers/SalesController.cs
using Microsoft.AspNetCore.Mvc;
using Infrastructure.ViewModels;
using UseCases.DataStorepluginInterfaces;
using UseCases.interfaces;
using UseCases.ProductsUseCases;
using Microsoft.AspNetCore.Authorization;

namespace Infrastructure.Controllers
{
    [Authorize(Policy = "Sales")]
    public class SalesController : Controller
    {
        private readonly IViewSelectedProductUseCase viewSelectedProductUseCase;
        private readonly IViewCategoriesUseCase viewCategoriesUseCase;
        private readonly ISellProductUseCase sellProductUseCase;
        private readonly IViewProductsInCategory viewProductsInCategory;

        public SalesController(IViewSelectedProductUseCase viewSelectedProductUseCase,
                               IViewCategoriesUseCase viewCategoriesUseCase,
                               ISellProductUseCase sellProductUseCase,
                               IViewProductsInCategory viewProductsInCategory)
        {
            this.viewSelectedProductUseCase = viewSelectedProductUseCase;
            this.viewCategoriesUseCase = viewCategoriesUseCase;
            this.sellProductUseCase = sellProductUseCase;
            this.viewProductsInCategory = viewProductsInCategory;
        }
        public IActionResult Index()
        {
            var salesViewModel = new SalesViewModel
            {
                Categories = viewCategoriesUseCase.Execute()
            };
            return View(salesViewModel);
        }

        public IActionResult DetailsBySelectedProductPartial(int productId)
        {
            var product = viewSelectedProductUseCase.Execute(productId);
            return PartialView("_ProductDetails", product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Sell(SalesViewModel salesViewModel)
        {
            var prod = viewSelectedProductUseCase.Execute(salesViewModel.SelectedProductId);

            if (ModelState.IsValid)
            {
                if (prod != null)
                {
                    sellProductUseCase.Execute("Cashier1", salesViewModel.QuantityToSell, salesViewModel.SelectedProductId);
                }
                return RedirectToAction(nameof(Index));
            }
            
            salesViewModel.SelectedCategoryId= (prod?.CategoryId==null)? 0:prod.CategoryId.Value;

            salesViewModel.Categories = viewCategoriesUseCase.Execute();
            return View("Index", salesViewModel);
        }

        public IActionResult ProductsByCategoryPartial(int categoryId)
        {
            var products = viewProductsInCategory.Execute(categoryId);
            return PartialView("_Products", products);
        }
    }
}

Infrastructure/ViewComponents/TransactionsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using UseCases.interfaces;

    namespace Infrastructure.ViewComponents
{
    public class TransactionsViewComponent:ViewComponent
    {
        private readonly ISearchTransactionUseCase searchTransactionUseCase;

        public TransactionsViewComponent(ISearchTransactionUseCase searchTransactionUseCase)
        {
            this.searchTransactionUseCase = searchTransactionUseCase;
        }

        public IViewComponentResult Invoke(string userName)
        {
            var transactions = searchTransactionUseCase.Execute(userName, DateTime.Today, DateTime.Now);

            return View(transactions);
        }
    }
}

Infrastructure/Views/Sales/Index.cshtml
@model SalesViewModel
@section title {
    <div class="row">
        <div class="col-7"> <h3>Cashier's Console</h3></div>
        <div class="col-2"><label for="cashier">Cashier Name:</label></div>
        <div class="col-3">
            @* Cashier's name is here *@
        </div>
    </div>
}

<div class="row">
</div>
<br />

<div class="row">
    <div class="col-4">
        <div class="text-danger" asp-validation-summary="All"></div>
        <select asp-for="SelectedCategoryId" class="form-control">
            <option>- Please Select -</option>
            @if (Model.Categories != null && Model.Categories.Count() > 0)
            {
                @foreach (var category in Model.Categories)
                {
                    <option value="@category.CategoryId"> @category.CategoryName</option>
                }
            }
        </select>
        <br />

        <div id="productsPartial">
            @* Product list *@
        </div>

        <br />

        <div id="productDetailsPartial">
            @* Product details *@
        </div>

        @* Sales form *@
        <form method="post" asp-controller="sales" asp-action="sell" id="formSale">
            <input asp-for="@Model.SelectedProductId" class="form-control" readonly type="hidden" />
            <div class="form-group">
                <label asp-for="@Model.QuantityToSell" class="form-label"></label>
                <input asp-for="@Model.QuantityToSell" class="form-control" type="number" min="1"/>
            </div>
            <span class="col text-danger" asp-validation-for="@Model.QuantityToSell"></span>

            <br />

            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Submit"/>
            </div>
        </form>
    </div>
    <div class="col">
        @* List of transactions *@

        @await Component.InvokeAsync("Transactions", "Cashier1")
    </div>
</div>

@section Scripts {
    <script>
        $(function () {
            $("#formSale").hide();
            $("#QuantityToSell").val("");

            var selectedCategoryId = $("#SelectedCategoryId").val();

            if(selectedCategoryId > 0){
                loadProducts(selectedCategoryId);
            }

            $("#SelectedCategoryId").on("change", function () {
                loadProducts($(this).val())
            }); 

            $("#productsPartial").on('click', '.product-row', function() {
                $('.product-row').removeClass('highlight');
                $(this).addClass('highlight');

                var productId = $(this).attr('product-id'); 

                $("#productDetailsPartial").load("/Sales/DetailsBySelectedProductPartial",
                { productId: productId });

                if(productId>0){
                    $("#SelectedProductId").val(productId)
                    $("#formSale").show();
                }
                else{
                    $("#SelectedProductId").val("")
                    $("#formSale").hide();
                }
            });
        });

        function loadProducts(categoryId){
            $("#productsPartial").load("/sales/ProductsByCategoryPartial", { categoryId: categoryId });
                  $("#productDetailsPartial").html("");
        }

    </script>
}

Infrastructure/Views/Sales/_ProductDetails.cshtml
@using CoreBusiness
@model Product

<div class="form-group">
    <label asp-for="@Model.Name" class="form-label"></label>
    <input asp-for="@Model.Name" class="form-control" type="text" readonly/>
</div>

<div class="form-group">
    <label asp-for="@Model.Price" class="form-label"></label>
    <input asp-for="@Model.Price" class="form-control" type="text" readonly value="@(string.Format("{0:c}", Model.Price))"/>
</div>

Infrastructure/Views/Sales/_Products.cshtml
@using CoreBusiness
@model IEnumerable<Product>

@if(Model != null && Model.Count() > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Quantity</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var product in Model)
            {
                <tr class="product-row" product-id="@product.ProductId">
                    <input type="hidden" asp-for="@product.ProductId" />
                    <th>@product.Name</th>
                    <th>@product.Quantity</th>
                </tr>
            }
        </tbody>

    </table>
}